name: signalr_core
description: ASP.NET Core SignalR Client written for Dart that is platform-independent, and can be used on both the command-line and the browser.
version: 1.1.0-nullsaftey
homepage: https://github.com/jamiewest/signalr_core

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  http: ^0.12.1
  logging: ^0.11.0
  meta: ^1.3.0-nullsafety.6
  tuple: ^2.0.0-nullsafety.0
  web_socket_channel: ^1.1.0
  sse_client: ^0.0.3
  equatable: ^2.0.0-nullsafety.1

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.15
