name: signalr_core
description: ASP.NET Core SignalR Client written for Dart that is platform-independent, and can be used on both the command-line and the browser.
version: 1.0.8
homepage: https://github.com/jamiewest/signalr_core

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  http: ^0.13.1
  logging: ^1.0.0
  meta: ^1.1.8
  tuple: ^2.0.0
  web_socket_channel: ^2.0.0
  sse_client: ^0.1.0
  equatable: ^2.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.2.0
